# 상수, 변수, 플레이스홀더

In [2]:
import tensorflow as tf

## 상수

``` py
tf.constant(
    value,
    dtype=None,
    shape=None,
    name='Const',
    verify_shape=False
)
```

텐서플로에서 상수는 고정값을 의미합니다. 값 자체는 행렬이거나 텐서여도 무관합니다.

행렬이나 텐서를 상수값으로 넣을때는 주로 넘피(numpy) 데이터형을 사용하게 됩니다. 이때 shape을 굳이 넣지 않아도 텐서플로는 자연스럽게 np.shape 값을 shape 값으로 기록하게 됩니다.

만약 shape값을 직접 지정해주었지만, value의 행렬크기가 더 클경우에는 오류를 반환합니다.
반대로, 지정된 shape값보다 value 행렬 크기가 작을 경우, 남은 공간들을 value에 가장 마지막 값으로 복사해 넣게됩니다.
verify_shape이 참(true)일 경우에는 shape값과 value의 행렬크기가 같지 않는 경우 모두 오류를 반환하게 됩니다.

In [28]:
tf.reset_default_graph()

x = tf.constant([1,4,3], shape=(3,3), name='x')
y = tf.constant(5, name='y')
z = tf.constant([[1,3],[2,5]])

sess = tf.Session()
print(x, '\n', sess.run(x))
print(y, '\n', sess.run(y))
print(z, '\n', sess.run(z))
sess.close()

Tensor("x:0", shape=(3, 3), dtype=int32) 
 [[1 4 3]
 [3 3 3]
 [3 3 3]]
Tensor("y:0", shape=(), dtype=int32) 
 5
Tensor("Const:0", shape=(2, 2), dtype=int32) 
 [[1 3]
 [2 5]]


## 플레이스홀더

``` py
tf.placeholder(
    dtype,
    shape=None,
    name=None
)
```

플레이스홀더는 계산중 입력값을 받는 변수입니다. 일반 변수와의 차이점은 플레이스홀더는 실행당시 직접 값을 넣어주어야 하지만 변수는 항상 어떠한 값을 가지고 있습니다.

플레이스홀더를 지정할때 가장 필수적인 요소는 데이터형입니다. 데이터를 입력받을 때 어떤 데이터형으로 받을지를 미리 정해두는 것은 추후에 생길 계산에 형변환 오류를 방지하기 위해서입니다.

플레이스홀더를 지정할때 사이즈에 None값을 사용할 수 있는데, None은 크기가 정해지지 않았다는 의미를 가지고 있습니다.

이런 방법을 사용하는 이유는 대부분 머신러닝을 할때 주어진 데이터 양이 일정하지 않기때문입니다.

대부분 플레이스홀더는 인풋(input)을 의미할때 사용하고, 사이즈는 대부분 [None, (input shape)] 을 사용합니다. 예를들어 인풋이 256x256 사이즈의 이미지일 경우 사이즈는 [None, 256, 256]을 사용합니다.

그래프를 실행할 때 플레이스홀더에 값을 넣는 방법은 세션을 실행하는 메소드인 run 안에 딕셔너리 형으로 넣는 방법입니다.

만약 입력된 데이터 값과 플레이스홀더의 shape이 맞지 않는 경우에는 오류를 반환합니다.

In [36]:
tf.reset_default_graph()

x = tf.placeholder(tf.int32, [None, 2])
x_data = [[1, 2], [3, 4], [5,6]]

sess = tf.Session()
print(sess.run(x, feed_dict={x:x_data}))
sess.close()

[[1 2]
 [3 4]
 [5 6]]


In [1]:

# tf.placeholder: 계산을 실행할 때 입력값을 받는 변수로 사용합니다.
# None 은 크기가 정해지지 않았음을 의미합니다.
X = tf.placeholder(tf.float32, [None, 3])
print(X)

# X 플레이스홀더에 넣을 값 입니다.
# 플레이스홀더에서 설정한 것 처럼, 두번째 차원의 요소의 갯수는 3개 입니다.
x_data = [[1, 2, 3], [4, 5, 6]]

# tf.Variable: 그래프를 계산하면서 최적화 할 변수들입니다. 이 값이 바로 신경망을 좌우하는 값들입니다.
# tf.random_normal: 각 변수들의 초기값을 정규분포 랜덤 값으로 초기화합니다.
W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([2, 1]))

# 입력값과 변수들을 계산할 수식을 작성합니다.
# tf.matmul 처럼 mat* 로 되어 있는 함수로 행렬 계산을 수행합니다.
expr = tf.matmul(X, W) + b

sess = tf.Session()
# 위에서 설정한 Variable 들의 값들을 초기화 하기 위해
# 처음에 tf.global_variables_initializer 를 한 번 실행해야 합니다.
sess.run(tf.global_variables_initializer())

print("=== x_data ===")
print(x_data)
print("=== W ===")
print(sess.run(W))
print("=== b ===")
print(sess.run(b))
print("=== expr ===")
# expr 수식에는 X 라는 입력값이 필요합니다.
# 따라서 expr 실행시에는 이 변수에 대한 실제 입력값을 다음처럼 넣어줘야합니다.
print(sess.run(expr, feed_dict={X: x_data}))

sess.close()


/Users/skim0119/Desktop/Project/ML_Library_Notes/venv/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


Tensor("Placeholder:0", shape=(?, 3), dtype=float32)
=== x_data ===
[[1, 2, 3], [4, 5, 6]]
=== W ===
[[ 0.26188758 -1.2323303 ]
 [-0.47956774  0.1896324 ]
 [-0.6941297  -0.268216  ]]
=== b ===
[[0.23171921]
 [0.53967345]]
=== expr ===
[[-2.5479176 -1.4259943]
 [-4.9753933 -5.0507817]]
