# 경사하강법

텐서플로는 다양한 최적화 방식들을 메소드로 구현해놓았다. 덕분에 덕분에 신경망을 구현할 때 백프로퍼게이션 과정을 쉽게 적용 가능하다.

경사하강법을 구현할때는 우선 그래프의 결과의 Loss의 척도를 정한 뒤, Loss를 최소화 하는 방향으로 진행한다.

In [1]:
import tensorflow as tf

/Users/skim0119/Desktop/Project/ML_Library_Notes/venv/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [21]:
tf.reset_default_graph()

x = tf.Variable(tf.truncated_normal((3,3)))
x_round = tf.round(x)
x_target = tf.eye(3)
loss = tf.reduce_mean(tf.square(x_target - x))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(loss)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(x))
for i in range(10000):
    sess.run(optimizer)

print(sess.run(x_round))
    
sess.close()

[[ 0.17974567 -1.5417141  -0.5885861 ]
 [ 0.23632607 -1.3352723   0.14424683]
 [-0.91812176 -1.5257802  -0.505787  ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
